project_id = "tbnlvdytmqjwcmxdogdj"

[functions.start-analysis]
verify_jwt = true

[functions.research-agent]
verify_jwt = true

[functions.analysis-agent]
verify_jwt = true

[functions.report-generator]
verify_jwt = true

[functions.deliver-report]
verify_jwt = true